### ISSUE TITLE
Move exit/entrance description to Route section

### ISSUE THREAD

**Issue by simgislab** [nextgis/metro4all#155]
Move text about exit/entrance to corresponding Route sections, use different style and font size.

After that - remove description fields under FROM and TO altogether.

**Comment by Kinda-me** [comment]
Done.

**Comment by Kinda-me** [comment]
If there's no exit/entrance descrition in chosen language, web app shows "name_en". Need to show the content of "name_en" field in this case.

http://metro4all.org/by/msk/#stat-start=2&route=1&portal-in=20090&stat-end=4&profile=man&portal-out=19210

![3](https://cloud.githubusercontent.com/assets/6493848/7134591/f65cee94-e2a6-11e4-82cb-5b79f0394ece.png)
