### ISSUE TITLE
Невыразительные значки выбора входа\выхода

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/metro4all#177]
При выборе входа\выхода новый пользователь, имхо, должен долго искать на карте маленькие невыразительные значки, которые вдобавок сливаются со схемой и цветастой подложкой OSM (скрин в приложении)
![snapshot_new1](https://cloud.githubusercontent.com/assets/1277422/5198816/d85751c6-7566-11e4-944f-33afc4b88fe4.png)

При первом заходе на карту вообще не очень понятно, что что-то нужно выбирать - я выбрал станцию, карта спозиционировалась, и я честно не увидел, что появились дополнительные значки (я вообще думал что они отрисованы на подложке).

ИМХО значки быть более броскими (гало, тень или псевдо 3д) а так же желательно выводить на карте небольшое сообщение о необходимости дополнительного выбора.

**Comment by Kinda-me** [comment]
Нужно сделать значки с номерами входов-выходов, аналогично мобильному приложению.

![screenshot_2015-01-27-12-43-12](https://cloud.githubusercontent.com/assets/6493848/5937557/f312ef80-a701-11e4-852e-dea076bbc8c9.png)
