### ISSUE TITLE
Плохое качество иконок с логотипами метрополитенов

### ISSUE THREAD

**Issue by drnextgis** [nextgis/metro4all#189]
Нормальные только в Екатеринбурге, Москве, Санкт-Петербурге, а в остальных городах выглядят плохо.

**Comment by simgislab** [comment]
желательно присылать свою версию SVG на пробу, в ней нужно избавляться от мелких деталей по аналогии с иконками, которые показываются хорошо

хотя бы по одной штуке

**Comment by KoGor** [comment]
И не забыть прогнать через оптимизатор SVG, например [SVGO](https://github.com/svg/svgo) или http://petercollingridge.appspot.com/svg-editor.

**Comment by Kinda-me** [comment]
http://petercollingridge.appspot.com/svg-editor - этим пробовали, не помогло.

**Comment by simgislab** [comment]
This issue was moved to nextgis/metro4all-android#12
