### ISSUE TITLE
Перевод благодарностей

### ISSUE THREAD

**Issue by drnextgis** [nextgis/metro4all#190]
Не понятно с чего вдруг внутри русскоязычной страницы присутствует кнопка с английским текстом и соответствующим текстом. Наверное, надо перевести.

**Comment by simgislab** [comment]
Будут:
Лицензиями/Licenses

но содержимое только на англ, это очень сложно поддерживать.

**Comment by 4eRTuk** [comment]
Кнопка переведена.
