### ISSUE TITLE
Улучшение кнопки с инвалидом

### ISSUE THREAD

**Issue by drnextgis** [nextgis/metro4all#191]
1. Сейчас вообще не понятно что это кнопка - выглядит как 3 иконки, болтающиеся в воздухе;
2. Если эта кнопка для задания профилей, то и должно открываться окно с настройками профилей, а не общее меню Настройки.

**Comment by simgislab** [comment]
формирую требования, как мне видятся:
- кнопка должна быть выполнена в виде переключателя-индикатора 
- должно быть понятно, что это переключатель (например иметь часть со светящейся палкой on/off)
- переключатель должен иметь разные иконки для состояний вкл/выкл (серая - голубоватая как сейчас)
- нажатие должно перебрасывать в очевидное место настроек
- соотв. изменение настроек должно отражаться на состояние индикатора

**Comment by Kinda-me** [comment]
- кнопка должна быть выполнена в виде переключателя-индикатора - сделано
- должно быть понятно, что это переключатель (например иметь часть со светящейся палкой on/off)
- переключатель должен иметь разные иконки для состояний вкл/выкл (серая - голубоватая как сейчас) - сделано
- нажатие должно перебрасывать в очевидное место настроек - сделано, настройки вынесены на отдельный экран
- соотв. изменение настроек должно отражаться на состояние индикатора - сделано
