### ISSUE TITLE
Неудобные кнопки с картой и схемой

### ISSUE THREAD

**Issue by drnextgis** [nextgis/metro4all#192]
Первый раз вообще не очевидно, что это кнопки, а при их использовании то и дело не попадаешь по ним.

**Comment by simgislab** [comment]
- кнопка должна быть выполнена в виде переключателя-индикатора 
- должно быть понятно, что это переключатель (например иметь часть со светящейся палкой on/off)
- переключатель должен иметь разные иконки для состояний вкл/выкл (серая - голубоватая как сейчас)
- нажатие должно перебрасывать в очевидное место настроек
- соотв. изменение настроек должно отражаться на состояние индикатора

**Comment by simgislab** [comment]
может просто сделать выпадашку и там написать словами
- map/plan
- карта/схема

**Comment by Kinda-me** [comment]
Можно "раскрывающуюся" кнопку, как в NG Mobile

![screenshot_2015-01-13-16-29-07](https://cloud.githubusercontent.com/assets/6493848/5726998/dc5fa02c-9b70-11e4-8877-236a7377b06f.png)

**Comment by Kinda-me** [comment]
Сейчас так:

![screenshot_2015-01-28-15-36-43](https://cloud.githubusercontent.com/assets/6493848/5937683/7c44c872-a703-11e4-895f-b14a7f166b70.png)
