### ISSUE TITLE
На списке станций иногда не работает кнопка показа схемы.

### ISSUE THREAD

**Issue by trolleway** [nextgis/metro4all#194]
Открываю первый попавшийся город (Казань)
Нажимаю в списке станций на правую иконку.
На некоторых станциях раскрывается список входов, на других станциях - появляется схема станции.

Ожидаемое поведение: для всех станций, по нажатию на правую иконку появляется схема.
Устройство: Wexler.tab 7t

**Comment by Kinda-me** [comment]
Исправлено.
