### ISSUE TITLE
Kazan data check (Kremlevskaya)

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/metro4all#195]
Сообщение с сайта: 
"Казань, станция Кремлевская
Вход 1 расположен не правильно, правильное расположение смотрите в OSM"

**Comment by simgislab** [comment]
@KolesovDmitry можешь как-нибудь глянуть, так ли это? Такое ощущение, что действительно совсем не там точки у нас, а еще пропущен один из выходов, который был закрыт когда мы это исследовали.

**Comment by KolesovDmitry** [comment]
Действительно, выход 1 "Площадь тысячелетия"  показывает куда-то не туда -- он должен смотреть в сторону Булака, а уходит, почему-то к Кремлю. Где править выходы?

А что касается того который был закрыт, когда мы его рисовали, так он закрыт до сих пор (и, думаю будет закрыт еще несколько лет -- он не открывался с 2005 года, когда сдали станцию)

**Comment by simgislab** [comment]
да, нужно снять с ОСМ и в таблице поменять координаты, этого достаточно

но у меня еще вопрос тогда про схему, получается что она у нас сейчас совсем не ориентирована на север, было бы неплохо это сделать.

также на ней надо проставить номер закрытого выхода

**Comment by KolesovDmitry** [comment]
Там была путаница с координатами и названиями выходов. Поправил csv, но изменений не вижу на сайте не вижу -- как было, так и осталось. Схема, которая хранится -- в PNG, а не в svg. Хранится ли в репозитории SVG?

**Comment by simgislab** [comment]
я обновлю на сервере, как схему поправим (отправил оригинал почтой)

**Comment by simgislab** [comment]
исправлено (возможно надо еще схему переориентировать)
