### ISSUE TITLE
Название текущего города на главной странице

### ISSUE THREAD

**Issue by drnextgis** [nextgis/metro4all#197]
Предлагаю на главной странице вместо бесполезной надписи Metro4All сделать индикатор текущего города, возможно с функцией его выбора прямо отсюда.

**Comment by simgislab** [comment]
Так и было в предыдущей версии, решили отказаться по следующим причинам:

- обычный пользователь хорошо понимает, в каком городе находится (соответственно эти данные он и загрузил) и ему не нужно об этом постоянно напоминать
- обычный пользователь не будет загружать несколько городов
- в будущих версиях приложения будет реализована прокладка маршрута совмещенная с главным экраном и тогда в заголовок уйдет выбор варианта маршрута, вместо надписи Metro4All

**Comment by simgislab** [comment]
This issue was moved to nextgis/metro4all-android#11
