### ISSUE TITLE
Отсортировать список выбора текущего города

### ISSUE THREAD

**Issue by drnextgis** [nextgis/metro4all#198]

**Comment by Kinda-me** [comment]
Отсортировать по алфавиту. Сейчас так:

![screenshot_2015-01-28-15-33-05](https://cloud.githubusercontent.com/assets/6493848/5937657/11b13c7a-a703-11e4-969a-3bcfcefa4452.png)

**Comment by simgislab** [comment]
fixed?

**Comment by 4eRTuk** [comment]
fixed.
