### ISSUE TITLE
е/ё в поиске

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/metro4all#199]
Для поиска станции "Тропарёво" нужно обязательно вводить её через "ё". Непонятно что делать тем, у кого, как у меня, на мобильной клавиатуре нет буквы "ё".

**Comment by BishopGIS** [comment]
Долгое нажатие на е на клавиатуре ставит ё

**Comment by drnextgis** [comment]
Да, у меня так же, мягкий и твёрдый знак работают аналогично.

**Comment by Kinda-me** [comment]
Еще дело в том, что какие-то станции у нас через "ё" (Тропарёво), а какие-то через "е" (Щелковская). Возможно ли делать общий поиск по е/ё, как сделано в вебе?

**Comment by 4eRTuk** [comment]
Сделано
