### ISSUE TITLE
Пересмотр структуры для порталов и пересадок

### ISSUE THREAD

**Issue by Zverik** [nextgis/metro4all#20]
Порталы и пересадки — суть одно и то же: пешеходный переход из точки A в точку B. Для пересадок A и B — идентификаторы станций, для порталов B — выход. При этом ограничения по направлению важны там и там: например, между станциями на пересадке может быть однонаправленный эскалатор.

Таблица portals.csv будет отдана _только_ под описание выходов: останутся столбцы `id_entrance;name;lat;lon`. Привязывать выходы к станциям возможно не везде, но для удобство в поле name можно хранить название станции (я так и делаю).

Идентификаторы выходов должны быть в одном пространстве с идентификаторами станций, т.е. не пересекаться с ними. Это можно сделать постобработкой данных google docs.

Таблицу interchanges.csv нужно переименовать в routes.csv (так проще), состав колонок до max_width (см. #18) будет таким: `id_from;id_to;direction;name`. Здесь идентификаторы могут быть как станций, так и выходов. Кроме того, могут быть _фиктивные идентификаторы_ для обозначения промежуточных точек: например, для выходов в подземные переходы можно разбить путь до двери и путь до поверхности.

При необходимости (хотя есть ли она?) можно добавить таблицу для фиктивных идентификаторов virtual.csv со столбцами `id_virtual;name`.

**Comment by simgislab** [comment]
This issue was moved to nextgis/metro4all-android#22
