### ISSUE TITLE
Limitations bug

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/metro4all#201]
Если количество ступеней без рельс и пандусов на участке маршрута = 0, то приложение не выводит информацию об этом, а показывает только общее количество ступеней и параметры рельс/пандусов.

Нужно:
- либо выводить строчку "из них без рельс и пандусов" в любом случае,
- либо не выводить ее только в том случае, когда количество ступеней без рельс и пандусов = общему количеству ступеней

![screenshot_2015-01-28-16-18-20](https://cloud.githubusercontent.com/assets/6493848/5938240/098f4b7a-a70a-11e4-8c76-e4537c4ab3d8.png)

**Comment by 4eRTuk** [comment]
сейчас выводится в любом случае строчка как в первом варианте.
