### ISSUE TITLE
Добавить возможность звонка на телефоны официальных служб помощи из мобильного приложения

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/metro4all#202]
Еще добавить остальную информацию по службам помощи отсюда - http://metro4all.org/ru/official-assistance/

**Comment by simgislab** [comment]
Кнопку с надписью "Официальная помощь" нужно добавить на экран Ограничения под сопроводительным текстом.

По нажатию на кнопку должно всплывать окно с текстом:
"Официальная служба помощи метрополитена города " [подставить]

Дальше, в зависимости от наличия информации в csv:

Телефон: +7 (495) 622-73-41 <- кликабельный и переносится в набор номера
Дополнительная информация:
Часы работы: с 10:00 до 17:00

и т.д.

**Comment by simgislab** [comment]
пример данных https://github.com/nextgis/metro4all/blob/master/data/min/official_help.csv

**Comment by 4eRTuk** [comment]
Сделано
