### ISSUE TITLE
Black arrow

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/metro4all#207]
![screenshot_2015-01-31-12-00-20](https://cloud.githubusercontent.com/assets/6493848/6066710/2ea372e8-ad80-11e4-99e8-fd56ff21ea61.png)

**Comment by simgislab** [comment]
fixed?

**Comment by Kinda-me** [comment]
It seems black elements appear randomly.

![screenshot_2015-02-20-14-34-31](https://cloud.githubusercontent.com/assets/6493848/6285510/bd1b49f4-b90d-11e4-92bf-c8b818c09fe4.png)

**Comment by drnextgis** [comment]
Не стрелки, но, похоже из той же серии баг.
![screenshot_2015-02-25-19-59-43](https://cloud.githubusercontent.com/assets/866124/6371819/0657040c-bd21-11e4-8446-5889b03cf5d7.png)

**Comment by simgislab** [comment]
This issue was moved to nextgis/metro4all-android#9
