### ISSUE TITLE
Старт приложения

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/metro4all#208]
В том случае, если интернет на мобильном устройстве номинально подключен, а фактически сигнал очень слабый и интернета нет, мобильное на старте сначала долго и безуспешно пытается получить информацию об обновлении данных. Если нажать на стрелку "обратно", чтобы прервать процесс, то остается экран с надписью "данные повреждены". Если после этого зайти в настройки и выйти из них обратно, то загружается нормальный главный экран.
 
![screenshot_2015-02-05-18-38-42](https://cloud.githubusercontent.com/assets/6493848/6066722/4670b4f8-ad80-11e4-818c-a42f725371ce.png)

**Comment by simgislab** [comment]
Да, сообщение "данные повреждены" не должно выдаваться, если загрузка meta.json или пакета с данными не удалась и есть нормальные данные загруженные до этого.

**Comment by simgislab** [comment]
This issue was moved to nextgis/metro4all-android#8
