### ISSUE TITLE
BE names are absent

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/metro4all#217]
Web app shows EN names of portals and stations instead of BE names.

![default](https://cloud.githubusercontent.com/assets/6493848/6392680/3b0486ee-bdd4-11e4-8e0c-e9df5a50da9f.png)

**Comment by drnextgis** [comment]
Нужно просто поменять в настройках сайта, чтобы при выборе белорусского языка URL принимал вид `/be/min/`, вместо текущего `/by/min/`.

**Comment by Kinda-me** [comment]
К сожалению, "просто" поменять это не получится - плагин для вордпресса не позволяет.

![prtscr capture](https://cloud.githubusercontent.com/assets/6493848/6411394/08416424-be89-11e4-9361-624fbd50decf.jpg)

Я думала, что достаточно будет заменить в странице language="by" на language="be"  (описание, как на сайт добавляются страницы приложения, здесь - https://github.com/nextgis/metro4all/wiki/Architecture-RU#%D0%92%D0%B5%D0%B1-%D1%81%D0%B0%D0%B9%D1%82), но нет, вот к чему это ведет:

![be](https://cloud.githubusercontent.com/assets/6493848/6411593/29108020-be8b-11e4-947c-605ecba7f216.png)
