### ISSUE TITLE
Strange exit #3 at Annino

### ISSUE THREAD

**Issue by simgislab** [nextgis/metro4all#223]
Route:

http://metro4all.org/msk/#stat-start=163&stat-end=3&route=1&profile=man

Scheme:

http://demo.nextgis.ru/metro4all/data/msk/schemes/125.png

Panoramas:

https://maps.yandex.ru/-/CVGD7YMK

Exit #3 seems out of place

**Comment by Kinda-me** [comment]
Fixed #3:

Map: 
http://metro4all.org/ru/msk/#stat-start=163&route=1

Panoramas: 
https://maps.yandex.ru/?text=%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F%2C%20%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0%2C%20%D0%A1%D0%B5%D1%80%D0%BF%D1%83%D1%85%D0%BE%D0%B2%D1%81%D0%BA%D0%BE-%D0%A2%D0%B8%D0%BC%D0%B8%D1%80%D1%8F%D0%B7%D0%B5%D0%B2%D1%81%D0%BA%D0%B0%D1%8F%20%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F%2C%20%D0%BC%D0%B5%D1%82%D1%80%D0%BE%20%D0%90%D0%BD%D0%BD%D0%B8%D0%BD%D0%BE&sll=37.596812%2C55.583657&ll=37.597842%2C55.583395&spn=0.005504%2C0.000605&z=18&l=map%2Cstv
