### ISSUE TITLE
Список схем не содержит названий станций

### ISSUE THREAD

**Issue by vvoovv** [nextgis/metro4all#226]
Ссылки на http://metro4all.org/ru/analytics/ на схемы станций ведут на список файлов в виде чисел. Непонятно, как решить такую, например, задачу: найти схему метро Борисово в Москве
@Kinda-me @simgislab

**Comment by Kinda-me** [comment]
Для этого нужно посмотреть id_node в этом файле: https://github.com/nextgis/metro4all/blob/master/data/msk/stations.csv

**Comment by vvoovv** [comment]
Я уже посмотрел. Это не user-friendly :)

**Comment by simgislab** [comment]
это машиночитаемые данные, им не обязательно быть читабельными глазами

**Comment by vvoovv** [comment]
Но ссылка на них ведёт с сайта. Я бы всё-таки предложил разместить список станций (user-friendly) со ссылками на схемы.

**Comment by simgislab** [comment]
но зачем, еще один файл который нам нужно будет поддерживать непонятно для кого?

**Comment by vvoovv** [comment]
Исключительно ради удобства и удовлетворённости посетителей сайта metro4all.org

Я искал схему Борисово. Попал на список файлов в виде чисел. Подумал, что схемы пронумерованы в порядке ввода станции в эксплуатацию, начиная с 1930-х годов. Оказалось - нет. Стал просматривать содержимое других директорий. Наткнулся на stations.csv. Тут снова загадка - id_station или id_node. Оказалось id_node.

Немного будет таких мотивированных посетителей сайта, как я.

Если переходить к решению, то список станций со ссылками на схему должен создаваться скриптом на основе stations.csv. Может, такой скрипт уже есть? Список станций должен быть на сайте или в вики github?

**Comment by simgislab** [comment]
казалось бы, почему не прочитать сначала описание
https://github.com/nextgis/metro4all/wiki/Data-structure-RU

пользователь всегда будет недоволен, это такой закон и ему всегда будет чего-то не хватать, если идти у каждого на поводу, то мы только тем и будем заниматься, что повторяющиеся поля в разные файлы добавлять.

нет проблем сделать скрипт, вопрос, кто этот скрипт будет поддерживать и запускать?

список станций тоже нужно поддерживать, в вики гитхаб это точно не нужно. 

мы же не компендулум станций метрополитенов делаем, это лучше в википедии делать.
