### ISSUE TITLE
The Polish language version is included  information in English

### ISSUE THREAD

**Issue by testarmy** [nextgis/metro4all#227]
On the Polish version http://metro4all.org/pl/waw/ information is posted in English: "Here you can find route from entrance (station) to exit (station) and learn about all obstacles that may conflict with your limitations along the way  Instructions for web app and Legend for layouts"

**Comment by Kinda-me** [comment]
@KrzysztofMadejski Can you please translate these 2 strings?

**Comment by KrzysztofMadejski** [comment]
Translation:
Poniżej zobaczysz swoją trasę od wejścia do wyjścia z metra. Poinformujemy Cię o wszystkich barierach, które możesz napotkać na swojej drodze. Zobacz [przewodnik "Jak korzystać z serwisu] oraz [opis stosowanych oznaczeń].

BTW: First link redirects to infographics in russian: http://metro4all.org/ru/instructions-for-web-app/

**Comment by Kinda-me** [comment]
Thank you, filled in the translations.

We also need the translation of the strings in this page - http://metro4all.org/pl/instructions-for-web-app/

**Comment by KrzysztofMadejski** [comment]
1) Wybierz jak się poruszasz?
2) Wybierz stację początkową
3) Wybierz wejście na mapie
4) Wybierz stację końcową
5) Wybierz wyjścia na mapie
6) Zobacz trasę, bariery i schematy stacji

**Comment by Kinda-me** [comment]
Translation is done.
