### ISSUE TITLE
Lack of street name under the "wejscie", "wyjscie" - only for Polish version 

### ISSUE THREAD

**Issue by testarmy** [nextgis/metro4all#229]
go to http://metro4all.org/pl/waw/#stat-start=2&route=1&stat-end=6&profile=wheelchair&portal-in=40060&portal-out=40280

Under the "wejście #2" and "Wyjście #1"lack of name of street
It should be seen as a street name like in English version

Windows 7 64-bit Firefox

**Comment by Kinda-me** [comment]
Can you post a screenshot? Works fine for me.

**Comment by testarmy** [comment]
![metro4all - streets names_en](https://cloud.githubusercontent.com/assets/11860622/7159242/0f0cbd40-e381-11e4-9e1a-c916bf3de40b.PNG)
![metro4all - streets names_pl](https://cloud.githubusercontent.com/assets/11860622/7159243/0f3708c0-e381-11e4-9ba3-ba19364ed8e3.PNG)

**Comment by testarmy** [comment]
OK, now I see it works also for me... The bug has been submitted few days ago, so could be fixed already

**Comment by Kinda-me** [comment]
Yep, it was fixed yestersay via https://github.com/nextgis/metro4all/commit/8bc5a9a5306f9c71b363ba0d5b1933403c50d057
