### ISSUE TITLE
Stroller or wheelchair width is resetted after changing entry

### ISSUE THREAD

**Issue by testarmy** [nextgis/metro4all#230]
1. set your track and select entries 
2. set width for your stroller or wheelchair 
3. choose other entry

stroller or wheelchair width is resetted. also occurs for changing stations.	
stroller or wheelchair width should be saved

Windows 7  Firefox
http://screencast.com/t/eNwsPh7D

**Comment by Kinda-me** [comment]
The ticket already exists - https://github.com/nextgis/metro4all/issues/151
