### ISSUE TITLE
Incorrect description of the entrance: the inquire applies the stroller , but the answer applies to wheelchair; the bug is only in Polish version

### ISSUE THREAD

**Issue by testarmy** [nextgis/metro4all#233]
1. Go to the page: http://metro4all.org/pl/waw/ - only for Polish version
2. Choose <from> (<stacja początkowa> for Polish version) and type ""Młociny"", entrance 1# 
3. Choose <to> (<stacja końcowa> for Polish version) and type ""Kabaty""
4 Choose <Limitations>: 101 for [stroller]

Wrong description of the entrance: "Szerokość wózka inwalidzkiego: do 90 cm" 
The correct description is:  "Szerokość wózka dziecięcego: do 90 cm"  or   "Szerokość wózka: do 90 cm" 

![bf052da5b356336bfedd1d1ba9376618](https://cloud.githubusercontent.com/assets/11860622/7160676/e2d460de-e38a-11e4-8975-befeac37d0a4.jpg)

**Comment by Kinda-me** [comment]
Changed the string to "Minimalna szerokość przejścia" (similar to android app).
