### ISSUE TITLE
GUI Problem with choosing a city after we click [Miasta]

### ISSUE THREAD

**Issue by testarmy** [nextgis/metro4all#237]
1. Go to http://metro4all.org/pl/ 
2.Choose city 
3. Click [Miasta]  http://m
![hidden menu](https://cloud.githubusercontent.com/assets/11860622/7180796/43c06ee6-e445-11e4-9d85-4b487eda0d60.png)
etro4all.org/pl/miasta/

**Comment by Kinda-me** [comment]
Fixed.
