### ISSUE TITLE
Позиционирование устройства на станции метрополитена по БС

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/metro4all#40]
Создать список базовых станций с привязкой к станциям метрополитена.
Далее учитывать и передавать на сервер статистику перемещения пользователей между станциями для учета при расчете маршрута (особенно актуально при переходах, где ведутся какие-то работы и полно народа).
Для создания списка используем:
- getNeighboringCellInfo()
- getCellLocation()

**Comment by simgislab** [comment]
This issue was moved to nextgis/metro4all-android#20
